#!/usr/bin/env node
/** Reuse the repository figure renderer; validate Reformation figures byte-for-byte. */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { FIGURE_TEMPLATES, figureOutputName, renderResourceFigure } from "../../scripts/resource-figure-kit.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const bootcamp = path.join(root, "AI_Harness_Bootcamp_2");
const checkOnly = process.argv.includes("--check");
const required = ["id", "role", "template", "title", "desc", "caption", "transcript", "eyebrow"];
const forbidden = ["246 kg", "1,404 kg", "3 minutes late", "PO-01", "SOURCE_EVIDENCE", "what we'll cover", "in this section"];
const retired = ["V-18", "RCPT-19", "YARD_WINDOW_NOTE", "L-11", "L-12", "L-13", "RULE.changed.md", "K-4", "20:50Z", "21:20Z", "1,584 kg", "1,650 kg"];

function fail(message) { throw new Error(message); }
function relative(file) { return path.relative(root, file); }
function assertText(text, label, moduleId) {
  for (const token of [...forbidden, ...(moduleId >= 2 ? retired : [])]) {
    if (text.includes(token)) fail(`${label}: forbidden or retired token ${JSON.stringify(token)}`);
  }
}
function markdownFiles(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap(entry => {
    const full = path.join(dir, entry.name);
    if (entry.isSymbolicLink()) return [];
    if (entry.isDirectory()) return markdownFiles(full);
    return entry.name.endsWith(".md") ? [full] : [];
  });
}
function within(parent, target) {
  const rel = path.relative(parent, target);
  return rel !== ".." && !rel.startsWith(`..${path.sep}`) && !path.isAbsolute(rel);
}
function processModule(dir) {
  const id = Number(path.basename(dir).slice(7, 9));
  const specPath = path.join(dir, "figures", "spec.json");
  const outputs = new Set();
  if (fs.existsSync(specPath)) {
    const spec = JSON.parse(fs.readFileSync(specPath, "utf8"));
    if (typeof spec.resourceId !== "string" || !spec.resourceId.trim()) fail(`${relative(specPath)}: missing resourceId`);
    if (!Array.isArray(spec.figures)) fail(`${relative(specPath)}: figures must be an array`);
    assertText(JSON.stringify(spec), relative(specPath), id);
    for (const figure of spec.figures) {
      const label = `${spec.resourceId}/${figure.id || "?"}`;
      for (const field of required) {
        if (typeof figure[field] !== "string" || !figure[field].trim()) fail(`${label}: missing ${field}`);
      }
      if (!/^[a-zA-Z0-9_-]+$/.test(figure.id)) fail(`${label}: unsafe figure ID`);
      if (!FIGURE_TEMPLATES.includes(figure.template)) fail(`${label}: unsupported template ${figure.template}`);
      const output = path.join(dir, "shared", "figures", figureOutputName(figure));
      if (outputs.has(output)) fail(`${label}: duplicate output ${relative(output)}`);
      outputs.add(output);
      const rendered = renderResourceFigure(figure, spec.resourceId);
      const bytes = Buffer.from(rendered.endsWith("\n") ? rendered : `${rendered}\n`);
      assertText(rendered, relative(output), id);
      if (checkOnly) {
        if (!fs.existsSync(output) || !fs.readFileSync(output).equals(bytes)) fail(`${relative(output)}: missing or stale generated figure; run node reformation/scripts/render_figures.mjs`);
      } else {
        fs.mkdirSync(path.dirname(output), { recursive: true });
        fs.writeFileSync(output, bytes);
      }
    }
  }
  for (const file of markdownFiles(dir)) {
    const text = fs.readFileSync(file, "utf8");
    for (const match of text.matchAll(/!\[([^\]]*)\]\(([^\s)]+)(?:\s+["'][^"']*["'])?\)/g)) {
      if (/^(?:https?:|data:)/i.test(match[2])) continue;
      const target = path.resolve(path.dirname(file), decodeURIComponent(match[2].split("#")[0]));
      if (!match[1].trim()) fail(`${relative(file)}: figure needs alternative text`);
      if (!within(dir, target) || !fs.existsSync(target)) fail(`${relative(file)}: missing or escaped image ${match[2]}`);
      if (target.endsWith(".svg") && path.basename(path.dirname(target)) === "figures" && !outputs.has(target)) {
        fail(`${relative(file)}: linked figure has no owning spec: ${match[2]}`);
      }
    }
  }
  return outputs.size;
}
try {
  if (process.argv.slice(2).some(arg => arg !== "--check")) fail("usage: render_figures.mjs [--check]");
  const modules = fs.readdirSync(bootcamp, { withFileTypes: true })
    .filter(entry => entry.isDirectory() && /^module-\d{2}-/.test(entry.name))
    .map(entry => path.join(bootcamp, entry.name)).sort();
  if (modules.length !== 10 || modules.some((dir, index) => Number(path.basename(dir).slice(7, 9)) !== index)) fail("expected all ten module directories, 00–09");
  let count = 0;
  for (const dir of modules) count += processModule(dir);
  console.log(`PASS: ${count} Reformation figures ${checkOnly ? "match generated bytes" : "rendered"}; local image links resolve`);
} catch (error) {
  console.error(`HOLD: ${error.message}`);
  process.exitCode = 1;
}
